### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 109

### ISSUE THREAD

**Issue by Z02X** [Getdeck/getdeck#111]
### What happened?

When I try to add k3s>extraArgs># with arg: --bind-address I get:

```
[DEBUG] Traceback (most recent call last):
  File "getdeck.provider.utility_provider", line 102, in _create
  File "getdeck.utils", line 131, in _execute
  File "codecs", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 109: invalid start byte

Traceback (most recent call last):
  File "getdeck.__main__", line 175, in main
  File "getdeck.api.utils", line 10, in wrapper
  File "getdeck.api.get", line 50, in run_deck
  File "getdeck.provider.k3d", line 64, in create
  File "getdeck.provider.utility_provider", line 116, in _create
  File "getdeck.provider.utility_provider", line 102, in _create
  File "getdeck.utils", line 131, in _execute
  File "codecs", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 109: invalid start byte
[CRITICAL] There was an error running deck: 'utf-8' codec can't decode byte 0xba in position 109: invalid start byte
```
I thought it was something in my file but that doesn't look to be so.

### What did you expect to happen?

It passes the command without error.

### What is the content of the Deckfile you are using?

```
version: "1"

# the cluster configuration across all decks
cluster:
  provider: k3d
  minVersion: 4.0.0
  name: kubeinator
  nativeConfig:
    apiVersion: k3d.io/v1alpha4
    kind: Simple
    servers: 1
    agents: 0
    kubeAPI:
      hostIP: "192.168.0.4"
      hostPort: "6443"
    image: rancher/k3s:v1.25.3-k3s1
    network: br0
    options:
      k3s: # options passed on to K3s itself
        extraArgs:
          - arg: --advertise-address=192.168.0.4
            nodeFilters:
            - server:*
    ports:
      # portainer
      - port: 9000:9000
      - port: 9443:9443
      - port: 8000:8000
      - port: '80:80' # web

decks:
  - name: homelab-test
    namespace: homelab-test
    sources:
    # test service
    - type: helm
      ref: https://portainer.github.io/k8s/
      chart: portainer
      releaseName: portainer
      parameters:
      - name: service.type
        value: LoadBalancer

```

### OS version

```

NAME=Slackware
VERSION="15.0"
ID=slackware
VERSION_ID=15.0
PRETTY_NAME="Slackware 15.0 x86_64 (post 15.0 -current)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:15.0"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
VERSION_CODENAME=current

```

### Anything else we need to know?

I am still trying to see if it's something wrong with my input. My goal is to set the IP to be different then the host IP but on the same subnet. I think it's quite possible that the error is just not being caught and crashing here, something like the IP I set is wrong but that output is getting lost.

**Comment by Schille** [comment]
I wonder how you managed to bypass the Deckfile validation for the `cluster.name` attribute. That is missing in your Deckfile.
When running your Deckfile with a recent version of `deck` I see the following error:
```bash
> deck get deck.yaml 
[INFO] Reading Deckfile: deck.yaml
[CRITICAL] There was an error running deck: 1 validation error for Deckfile_1_0
cluster -> name
  field required (type=value_error.missing)
```
@buschNT any idea?

**Comment by buschNT** [comment]
> @buschNT any idea?

@Schille No, currently not. It should always throw the validation error from above when the cluster name is missing.

---

The `UnicodeDecodeError` is raised by the following part in the code:
```
            if print_output:
                for stdout_line in iter(process.stdout.readline, ""):
                    print(stdout_line, end="", flush=True)
```
This is "only" some output printing which is coupled to the logging.DEBUG level (`print_output=True if logger.level == logging.DEBUG else False,`). @Z02X I guess you used the "-d" flag when running the get command. Maybe it works without the debug output? Nevertheless, even without knowing the exact cause of the `UnicodeDecodeError`, this part of the code should not raise an error.

**Comment by buschNT** [comment]
@Schille #112 this is a small fix which should prevent getdeck from crashing at this point.

**Comment by Z02X** [comment]
> I wonder how you managed to bypass the Deckfile validation for the `cluster.name` attribute. It is missing in your Deckfile.
> When running your Deckfile with a recent version of `deck` I see the following error:
> ```bash
> > deck get deck.yaml 
> [INFO] Reading Deckfile: deck.yaml
> [CRITICAL] There was an error running deck: 1 validation error for Deckfile_1_0
> cluster -> name
>   field required (type=value_error.missing)
> ```
> @buschNT any idea?

Sorry I think I cut down the deck file a little to much. I will run a test on a less striped down one.

**Comment by Z02X** [comment]
The fix https://github.com/Getdeck/getdeck/pull/112 got me to a state where I can see what's going on now instead of crashing so I consider this fixed.
