### ISSUE TITLE
Tooler not able to add helm repos

### ISSUE THREAD

**Issue by Opswatch** [Getdeck/getdeck#128]
### What happened?

Trying to add help repo getting a context deadline exceeded, tried to add a helm repo from within the tooler container got the same error, happens with any helm repo, im able to ping out of the container with no issues as well as curl the helm repos but doing a helm repo add just times out, any ideas?

### What did you expect to happen?

Able to add helm repo

### How can we reproduce it (as minimally and precisely as possible)?

Hard to say

### What is the content of the Deckfile you are using?

cluster:
  provider: k3d
  minVersion: 4.0.0
  name: kubeinator
  nativeConfig:
    apiVersion: k3d.io/v1alpha4
    kind: Simple
    servers: 1
    agents: 1
    kubeAPI:
      hostPort: "6445"
    image: rancher/k3s:v1.22.9-k3s1
    ports:
      - port: 61346:80
        nodeFilters:
          - loadbalancer
      - port: 31820:31820
        nodeFilters:
          - agent:0

decks:
  - name: portainer
    namespace: portainer
    sources:
    - type: helm
      ref: https://portainer.github.io/k8s/ # latest, alpha
      chart: portainer
      releaseName: portainer
      parameters:
      - name: tls.force
        value: true

### OS version

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Linux summit-docker-testing-2 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by buschNT** [comment]
@Opswatch Thanks for reporting this issue. I tried to reproduce the error, but your deck.yaml seems to be working just fine. Thus, currently it's hard for me to pinpoint the issue. Searching for "helm context deadline exceeded" results in issues which are caused by the cluster or helm itself. I guess you already tried to remove the cluster and create a new one?

**Comment by Opswatch** [comment]
Hey, thanks for double checking, I did try to remove and recreate the cluster, its running in a test vm so maybe something funky with the environment, ill spin another one up and see if I can replicate it :)

**Comment by Opswatch** [comment]
Interesting so on my windows linux subsystem it works fine, not on the vm, ill keep digging.

**Comment by Opswatch** [comment]
Looks like its related to any charts hosted on github.io not sure why, seems like a enviromental issue, closing this ticket.

**Comment by buschNT** [comment]
Thanks for reporting/documenting your further testing here. I guess we will observe this issue and see if more people have similar troubles.
