### ISSUE TITLE
Add entries to /etc/hosts

### ISSUE THREAD

**Issue by georgkrause** [Getdeck/getdeck#21]
Usually we use nip.io to rebind Domains to hosts, which is a nice tool. However, this wont always work: It requires a free internet connection and DNS servers which do not block DNS rebinding. So we might want to provide an alternative to make getdeck work.

An idea would be to extract the URLs from the deck files and write the specified hosts to `/etc/hosts` on Linux, probably also works on Mac and we would need to do some research to find a solution for windows as well.

**Comment by Schille** [comment]
@schwobaseggl isn't this a problem on your site, too?

**Comment by buschNT** [comment]
Closed by #56
