### ISSUE TITLE
Run with private repos

### ISSUE THREAD

**Issue by SteinRobert** [Getdeck/getdeck#43]
Is there a way to run `deck get` with private repositories?

**Comment by Schille** [comment]
At least for Git locations you can access private repositories as long as the calling user's Git identity has access to it.
Please see https://getdeck.dev/docs/deckfile/specs#deckfile-location

**Comment by buschNT** [comment]
@SteinRobert I just wanted to ask if the response from @Schille answered your question?

**Comment by SteinRobert** [comment]
Yes, thanks!
