### ISSUE TITLE
Support for empty CLI Deckfile positional argument

### ISSUE THREAD

**Issue by buschNT** [Getdeck/getdeck#59]
E.g. the following commands are not working without and additional ".".

```
deck get
deck remove --cluster
```

If the positional argument "Deckfile" is not provided, getdeck could default to the CWD.

**Comment by Schille** [comment]
Makes sense :+1:

**Comment by buschNT** [comment]
True, I will fix this

**Comment by buschNT** [comment]
fixed via #103
