### ISSUE TITLE
Support relative file system paths when Deckfile is loaded via Git

### ISSUE THREAD

**Issue by Schille** [Getdeck/getdeck#81]
It is possible to load a Deckfile via Git like so `deck get git@mygithost.com/repo.git#branch`. This loads the _Deckfile_ and processes it accordingly.
When there are relative file system paths included in the _sources_ this won't work as the repo is not present on the local machine. Same with other sources.

**Comment by buschNT** [comment]
@Schille I just tested this issue on the "81" branch using the current "main" branch from getdeck:
`deck get git@github.com:Getdeck/getdeck.git#81`
The new deckfile at the root of the branch 81 has a local file reference which works. This issue might be solved by the refactoring we did.
Please feel free to try to reproduce this issue using other sources.

**Comment by Schille** [comment]
This is awesome.
